### ISSUE TITLE
Is DNA a preparation?

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/dina-model-concepts#31]
From @jmacklin : Is DNA a preparation? It is sampled from an object and then is either a preparation that is destroyed or a preparation that is a tube stored in a  freezer. Makes sense as you would need to sub-sample from the tube to do another analysis. Support Biobanking.

**Comment by falkogloeckler** [comment]
As of discussion in issue #45 
* we only define preparation processes
* preparation processes can be destructive, so a physical (sub-)entity is taken from a physical entity that could lead to a catalogued object or not
* DNA sampling is a preparation process
* DNA sample is a physical entity that could be consumed after analyses or could be accessioned in a biobank. So it could become a catalogued object.

@jmacklin & all: If you agree with the summary this issue can be closed

**Comment by jmacklin** [comment]
Agreed!

**Comment by cgendreau** [comment]
Do we have it explicitly explained in the information model?

**Comment by falkogloeckler** [comment]
> Do we have it explicitly explained in the information model?

We don't, but implicitly it is covered. However, I addressed DNA sampling as an example now. See patch:  https://github.com/DINA-Web/dina-model-concepts/pull/51

**Comment by cgendreau** [comment]
Merged the PR and closing the issue since we all agree.
