### ISSUE TITLE
Ducplication in Preparations component description

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/dina-model-concepts#44]
Component Description: Physical Entity:
-  Current state of the physical entity

Component Description: Preparations:
- state of the entity

Looks like a mistake, I don't think Preparations should track the state since it represents a state itself.

**Comment by jmacklin** [comment]
I think you are correct. However, it may depend on what we mean by "state".

**Comment by cgendreau** [comment]
From Physical Entity: `Current state of the physical entity (preserved, destroyed, contaminated, consumed, lost ...) `

**Comment by cboelling** [comment]
In our discussion on 2020/11/04 I pointed out that the term "preparation" is ambiguous and we clarified that *preparation* refers to the process of preparing and should be renamed to "preparation process". Consequently, object states like the ones [mentioned above](https://github.com/DINA-Web/dina-model-concepts/issues/44#issuecomment-719524847) ought to be associated with *Physical Entities*, not with *Preparation Processes*.

**Comment by cgendreau** [comment]
Preparation is now renamed to Preparation Process by https://github.com/DINA-Web/dina-model-concepts/pull/47

**Comment by falkogloeckler** [comment]
Agreed. So can be closed.
