### ISSUE TITLE
Preparation from another preparation

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/dina-model-concepts#45]
In the current component descriptions there is no mention of preparation based on another preparation. This was discussed so we should add it to the file. My understanding is yes, this should be there for multiple use cases including DNA extraction and what is described in AAFC Requirement in #35

**Comment by jmacklin** [comment]
Yes, correct and this will be quite a common practice. We have now agreed that the preparation is central to resampling and not the physical entity or catalogued object directly. So examples can be separated into the two different cases.

Preparation of a Physical Entity:
- A malaise trap of insects where resampling happens by different researchers interested in different taxa over time
- A lot of fishes preserved in alcohol where 1 is removed for DNA sampling and another for clearing and staining
- An unaccessioned bag of seeds associated with a botanical collection where one is removed for DNA analysis and another for SEM analysis
-A slab of rock containing fossils where a fossil is removed and prepared for study; at a later day a different fossil is removed.
- A soil or water sample that is resampled over time to target specific taxa or to use a new method/technology

Preparation of a Catalogued Item:
- an accessioned insect where a leg is removed for DNA analysis
- an accessioned insect where pollen is removed from the legs and analysed
- an accessioned plant specimen where a leaf is removed for DNA analysis
- an accessioned plant specimen where a leaf is removed for examining its endomycorrhizal associated fungi
- an accessioned fossil is polished and an acetate peel is taken to examine internal structures
- an accessioned living culture of a fungi is resampled as part of a curatorial process

**Comment by dshorthouse** [comment]
Looks like we're using `Preparation` as a noun in this ticket rather than as a `PreparationProcess`. So, this is really about differentiating the processes that are distinct: (1) One `PreparationProcess` tightly associated with Collecting Event, (2) Other `PreparationProcesses` executed once the Physical Entity is in-house, in the collection.

**Comment by jmacklin** [comment]
Agree with use of PreparationProcess. Although the processes themselves differ, the only distinction is that one has a catalogue number and the other (Physical Entities) do not. However, is it always the case that a Preparationprocess leads to a catalogued object, and does this fact matter? It may to the model. A physical entity could be subdivided into many sub samples none of which are accessioned. This is just done as a sorting exercise for later research purposes. Another related question is can a catalogued object be sampled from to create a physical entity that is not a new catalogued object? I can't think of any but we should consider if any use cases exist for this.

**Comment by dshorthouse** [comment]
@jmacklin Isn't such a scenario where physical entity is created from catalogued object (without it too being catalogued) standard practice with DNA barcoding?

**Comment by jmacklin** [comment]
@dshorthouse Good point! Couple of scenarios here. There is a destructive sample (this is the PreparationProcess) where the sample is fully consumed with result being a DNA sequence. The DNA sequence would not have a catalogue number but it would have to exist in ID only as a physical entity to maintain provenance. There is a destructive sample where some of the sample may still exist after processing. So there would be a child catalogued object and a DNA sequence. A very similar case would be a destructive sample where there is some sample left but the remaining sample is re-associated with the original sample, so no new catalogued object. So, every sample made is a physical entity and some may also be a catalogued object...  Now with new tech we can take a catalogued object and non-destructively collect material that DNA can be extracted from (e.g., an insect placed in a buffer solution and lightly shaken, then dried and put back in the collection). So, for provenance we have to generate a physical entity that holds the link to the DNA sequence derivative...? Of course, there are more cases of sampling that would follow these patterns. Feel like I need a whiteboard ;-)

**Comment by cgendreau** [comment]
But just to conclude on that ticket, "Preparation from another preparation" is not required since we should see it as a PreparationProcess. Therefore a PreparationProcess will always be linked to something (PhysicalEntity) that may or may not be the result of another PreparationProcess.

**Comment by jmacklin** [comment]
Yes, a "process" is not an object and therefore must be linked to a PhysicalEntity as far as I understand it now.

**Comment by falkogloeckler** [comment]
Please close if my last commit addresses the issue sufficiently.
