### ISSUE TITLE
Transactions, loans, requests

### ISSUE THREAD

**Issue by falkogloeckler** [DINA-Web/dina-model-concepts#52]
Metadata about loan requests is probably always very similar to other transactions (e.g. requests for digitization).
Thus, we might want to have a more generic approach to model these.

For example:
A digitization request for a certain object has been made by a person at a certain point in time, with a certain purpose. All the metadata on that request would be the same if the request for a loan, but the type of request and subsequent metadata on issuing the request. 
The related (linked) information on the object's availability before and after issuing the request would be the same. So, for example the availability of the object: The object needs to be available in order to be borrowed or digitized on demand. During loan and during digitization the object is (temporarily) not available anymore for issuing any other request (but the duration between request and return would be different). 
Thus, issuing digitization on demand could be considered an internal loan. This would be also true for conservational treatments (or preparation processes in general).

Any objections? 

I tried to approach this in the first draft on loan requests https://github.com/DINA-Web/dina-model-concepts/blob/falkogloeckler-comp-loans/component_descriptions/loans_and_requests.md 
If the generic approach is going to be adopted then the component definition should be renamed to a broader term like "transactions" or "requests" (instead of "loans").

**Comment by cboelling** [comment]
To me this approach is quite plausible. If the in the context of loans documentation of clearance, terms of use, other legal framing erwork is a requirement this might require some extra steps for those types of transactions.

**Comment by falkogloeckler** [comment]
solved in #55
